#!/bin/bash

# Start Airflow Webserver and Scheduler
# Credentials are auto-generated by Simple Auth Manager and stored in:
# $AIRFLOW_HOME/simple_auth_manager_passwords.json.generated

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

cd "$PROJECT_ROOT"

export AIRFLOW_HOME=${AIRFLOW_HOME:-$PROJECT_ROOT/airflow}

source venv/bin/activate

# Kill existing Airflow processes if running
echo "Checking for existing Airflow processes..."
pkill -f "airflow api-server" 2>/dev/null && echo "  Stopped existing api-server"
pkill -f "airflow scheduler" 2>/dev/null && echo "  Stopped existing scheduler"
pkill -f "airflow standalone" 2>/dev/null && echo "  Stopped existing standalone"
pkill -f "airflow triggerer" 2>/dev/null && echo "  Stopped existing triggerer"
pkill -f "airflow dag-processor" 2>/dev/null && echo "  Stopped existing dag-processor"
# Also check for old webserver command (Airflow 2.x compatibility)
pkill -f "airflow webserver" 2>/dev/null && echo "  Stopped existing webserver (legacy)"
# Wait for processes to fully terminate
sleep 3

# Initialize Airflow database if needed
if [ ! -f "$AIRFLOW_HOME/airflow.db" ]; then
    echo "Initializing Airflow database..."
    airflow db migrate
    echo ""
fi

echo "=== Starting Airflow ==="
echo "AIRFLOW_HOME: $AIRFLOW_HOME"
echo "Access: http://localhost:8080"
echo ""
echo "Starting Airflow API server, scheduler, and dag-processor..."
echo "Press Ctrl+C to stop"
echo ""

# Start API server in background (Airflow 3.0+)
# Use explicit host binding to 127.0.0.1 to avoid binding issues
airflow api-server --port 8080 --host 127.0.0.1 > "$AIRFLOW_HOME/api-server.log" 2>&1 &
API_SERVER_PID=$!

# Start dag-processor in background (required for DAG parsing in Airflow 3.0+)
airflow dag-processor &
DAG_PROCESSOR_PID=$!

# Wait a moment for API server and dag-processor to start
# API server may need extra time to initialize, especially with FAB auth manager
sleep 10

# Start scheduler in foreground (so we can Ctrl+C to stop)
airflow scheduler
